language:
  - java
deploy:
  provider: gae
  keyfile: api-sbnaukma-b949b0f52c7d.json
  project: api-sbnaukma
before_install:
- openssl aes-256-cbc -K $encrypted_ce88426e39f1_key -iv $encrypted_ce88426e39f1_iv
  -in api-sbnaukma-b949b0f52c7d.json.enc -out api-sbnaukma-b949b0f52c7d.json -d
